using System.Windows;

namespace BooruFrame;

/// <summary>
/// Lightweight runtime localization. Strings live in a ResourceDictionary merged into the
/// app resources so XAML can bind via {DynamicResource key}; switching language swaps the
/// values in place and DynamicResource re-resolves. Code can also read strings via Get().
/// </summary>
public static class Localization
{
    public enum Lang { Ru, Pl, En }

    public static Lang Current { get; private set; } = Lang.Ru;

    /// <summary>Raised after the language changes so code-driven text can be refreshed.</summary>
    public static event Action? Changed;

    private static ResourceDictionary? _dict;

    public static string Get(string key) =>
        Tables[Current].TryGetValue(key, out var v) ? v : key;

    public static void Apply(Lang lang)
    {
        Current = lang;

        if (_dict is null)
        {
            _dict = new ResourceDictionary();
            Application.Current.Resources.MergedDictionaries.Add(_dict);
        }

        _dict.Clear();
        foreach (var kv in Tables[lang])
            _dict[kv.Key] = kv.Value;

        Changed?.Invoke();
    }

    public static Lang Parse(string? s) => s switch
    {
        "Pl" => Lang.Pl,
        "En" => Lang.En,
        _ => Lang.Ru,
    };

    /// <summary>Best-effort match of the OS UI language; falls back to English.</summary>
    public static Lang FromSystem()
    {
        var code = System.Globalization.CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
        return code switch
        {
            "ru" => Lang.Ru,
            "pl" => Lang.Pl,
            _ => Lang.En,
        };
    }

    private static readonly Dictionary<Lang, Dictionary<string, string>> Tables = new()
    {
        [Lang.Ru] = new()
        {
            ["L_Tags"] = "Теги:",
            ["L_Sites"] = "Сайты — рандом из отмеченных:",
            ["L_AddSite"] = "＋ Добавить сайт",
            ["L_Filter"] = "Фильтр:",
            ["L_FilterNone"] = "Без фильтра (всё)",
            ["L_FilterModerate"] = "Умеренно (без explicit)",
            ["L_FilterAggressive"] = "Строго (только SFW)",
            ["L_FilterCustom"] = "Свои рейтинги",
            ["L_ExcludeRatingsHint"] = "Отметьте рейтинги, которые исключить из поиска:",
            ["L_IncludeTags"] = "Добавлять теги в каждый поиск:",
            ["L_ExcludeTags"] = "Исключать теги из каждого поиска:",
            ["L_Preview"] = "Превью запроса:",
            ["L_TipDownload"] = "Скачать картинку",
            ["S_Saved"] = "Картинка сохранена",
            ["L_Scale"] = "Масштаб:",
            ["L_ScaleFit"] = "Вписать",
            ["L_ScaleStretch"] = "Растянуть",
            ["L_ScaleCover"] = "Заполнить (кроп)",
            ["L_Interval"] = "Интервал:",
            ["L_HideErrors"] = "Прятать ошибки:",
            ["L_Never"] = "никогда",
            ["L_NoRepeat"] = "Не повторять картинку:",
            ["L_Off"] = "выкл",
            ["U_Changes"] = "смен",
            ["L_HideAnim"] = "Скрыть анимацию загрузки",
            ["L_DesktopFrame"] = "Рамка на фоне (без обычного окна)",
            ["L_DesktopFrameHint"] = "Рамка перестаёт быть обычным окном: нет кнопки на панели задач и в Alt+Tab, при потере фокуса она уходит на фон под все окна. Клик по рамке снова поднимает её. В режиме обоев не действует — там окно всегда обычное.",
            ["L_Wallpaper"] = "Режим обоев (вместо окна)",
            ["L_WallpaperHint"] = "Картинка становится живыми обоями рабочего стола — отдельным слоем за значками. Само приложение уходит в трей: окно можно открыть в любой момент, и это будет обычное полноценное окно. Родные обои Windows не меняются. Выход: Ctrl+Alt+F или пункт в трее.",
            ["L_Settings"] = "Настройки",
            ["L_Close"] = "Закрыть",
            ["L_TabSources"] = "Исходники",
            ["L_TabDisplay"] = "Отображение",
            ["L_TabInfo"] = "Информация",
            ["L_TagsHint"] = "Применяются ко всем сайтам",
            ["L_Language"] = "Язык:",
            ["L_InfoName"] = "Название:",
            ["L_InfoVersion"] = "Версия:",
            ["L_InfoAuthor"] = "Автор:",
            ["L_InfoRepo"] = "Репозиторий:",
            ["L_InfoSupport"] = "Поддержать:",
            ["L_TipPrev"] = "Прошлая картинка",
            ["L_TipNext"] = "Следующая картинка",
            ["L_TipPlay"] = "Старт",
            ["L_TipStop"] = "Стоп",
            ["L_TipSettings"] = "Настройки",
            ["L_Aspect"] = "Ориентация:",
            ["L_AspectAny"] = "Все",
            ["L_AspectLandscape"] = "Горизонтальные",
            ["L_AspectPortrait"] = "Вертикальные",
            ["L_AspectSquare"] = "Квадратные",
            ["L_TipMin"] = "Свернуть",
            ["L_TipMax"] = "Развернуть",
            ["L_TipRestore"] = "Восстановить",
            ["L_TipClose"] = "Закрыть",
            ["L_Start"] = "▶ Старт",
            ["L_Stop"] = "⏹ Стоп",
            ["L_Next"] = "⟳ Следующая",
            ["L_EditorNew"] = "Новый сайт",
            ["L_EditorEdit"] = "Изменить сайт",
            ["L_Name"] = "Название:",
            ["L_Engine"] = "Движок:",
            ["L_Url"] = "URL сайта:",
            ["L_Login"] = "login / user_id:",
            ["L_ApiKey"] = "api_key:",
            ["L_KeysHint"] = "Ключи нужны для Gelbooru/Rule34; Danbooru и Safebooru работают без них",
            ["L_Cancel"] = "Отмена",
            ["L_Save"] = "Сохранить",
            ["L_EditTip"] = "Изменить",
            ["L_DeleteTip"] = "Удалить",
            ["S_Initial"] = "Введите теги и нажмите «Следующая»",
            ["S_Loading"] = "Загрузка…",
            ["S_Nothing"] = "Ничего не найдено по этим тегам",
            ["S_NoPreset"] = "Отметьте хотя бы один сайт",
            ["S_WallpaperFail"] = "Не удалось включить режим обоев (слой рабочего стола не найден).",
            ["S_WallpaperFailAttach"] = "Не удалось включить режим обоев: Windows не дала встроить окно в рабочий стол. Попробуйте перезапустить проводник (explorer.exe) и запускать BooruFrame без прав администратора.",
            ["S_ErrNet"] = "Сетевая ошибка: {0}",
            ["S_ErrGel"] = "Gelbooru требует API-ключи. Откройте настройки сайта и укажите user_id + api_key.",
            ["U_Sec"] = "сек",
            ["U_Min"] = "мин",
            ["Tray_Show"] = "Показать окно",
            ["Tray_Hide"] = "Скрыть окно",
            ["Tray_Wallpaper"] = "Режим обоев",
            ["Tray_Prev"] = "Прошлая картинка",
            ["Tray_Exit"] = "Выход",
        },
        [Lang.Pl] = new()
        {
            ["L_Tags"] = "Tagi:",
            ["L_Sites"] = "Strony — losowanie z zaznaczonych:",
            ["L_AddSite"] = "＋ Dodaj stronę",
            ["L_Filter"] = "Filtr:",
            ["L_FilterNone"] = "Bez filtra (wszystko)",
            ["L_FilterModerate"] = "Umiarkowany (bez explicit)",
            ["L_FilterAggressive"] = "Ścisły (tylko SFW)",
            ["L_FilterCustom"] = "Własne oceny",
            ["L_ExcludeRatingsHint"] = "Zaznacz oceny do wykluczenia z wyszukiwania:",
            ["L_IncludeTags"] = "Dodawaj tagi do każdego wyszukiwania:",
            ["L_ExcludeTags"] = "Wykluczaj tagi z każdego wyszukiwania:",
            ["L_Preview"] = "Podgląd zapytania:",
            ["L_TipDownload"] = "Pobierz obraz",
            ["S_Saved"] = "Obraz zapisany",
            ["L_Scale"] = "Skalowanie:",
            ["L_ScaleFit"] = "Dopasuj",
            ["L_ScaleStretch"] = "Rozciągnij",
            ["L_ScaleCover"] = "Wypełnij (kadr)",
            ["L_Interval"] = "Interwał:",
            ["L_HideErrors"] = "Ukryj błędy po:",
            ["L_Never"] = "nigdy",
            ["L_NoRepeat"] = "Nie powtarzaj obrazu:",
            ["L_Off"] = "wył.",
            ["U_Changes"] = "zmian",
            ["L_HideAnim"] = "Ukryj animację ładowania",
            ["L_DesktopFrame"] = "Ramka na pulpicie (bez zwykłego okna)",
            ["L_DesktopFrameHint"] = "Ramka przestaje być zwykłym oknem: brak przycisku na pasku zadań i w Alt+Tab, po utracie fokusu opada na tło pod wszystkie okna. Kliknięcie ramki znów ją podnosi. W trybie tapety nie działa — tam okno jest zawsze zwykłe.",
            ["L_Wallpaper"] = "Tryb tapety (zamiast okna)",
            ["L_WallpaperHint"] = "Obraz staje się żywą tapetą pulpitu — osobną warstwą za ikonami. Sama aplikacja chowa się do zasobnika: okno można otworzyć w każdej chwili i jest to zwykłe, pełne okno. Natywna tapeta Windows nie jest zmieniana. Wyjście: Ctrl+Alt+F lub pozycja w zasobniku.",
            ["L_Settings"] = "Ustawienia",
            ["L_Close"] = "Zamknij",
            ["L_TabSources"] = "Źródła",
            ["L_TabDisplay"] = "Wyświetlanie",
            ["L_TabInfo"] = "Informacje",
            ["L_TagsHint"] = "Dotyczy wszystkich stron",
            ["L_Language"] = "Język:",
            ["L_InfoName"] = "Nazwa:",
            ["L_InfoVersion"] = "Wersja:",
            ["L_InfoAuthor"] = "Autor:",
            ["L_InfoRepo"] = "Repozytorium:",
            ["L_InfoSupport"] = "Wesprzyj:",
            ["L_TipPrev"] = "Poprzedni obraz",
            ["L_TipNext"] = "Następny obraz",
            ["L_TipPlay"] = "Start",
            ["L_TipStop"] = "Stop",
            ["L_TipSettings"] = "Ustawienia",
            ["L_Aspect"] = "Orientacja:",
            ["L_AspectAny"] = "Wszystkie",
            ["L_AspectLandscape"] = "Poziome",
            ["L_AspectPortrait"] = "Pionowe",
            ["L_AspectSquare"] = "Kwadratowe",
            ["L_TipMin"] = "Minimalizuj",
            ["L_TipMax"] = "Maksymalizuj",
            ["L_TipRestore"] = "Przywróć",
            ["L_TipClose"] = "Zamknij",
            ["L_Start"] = "▶ Start",
            ["L_Stop"] = "⏹ Stop",
            ["L_Next"] = "⟳ Następny",
            ["L_EditorNew"] = "Nowa strona",
            ["L_EditorEdit"] = "Edytuj stronę",
            ["L_Name"] = "Nazwa:",
            ["L_Engine"] = "Silnik:",
            ["L_Url"] = "URL strony:",
            ["L_Login"] = "login / user_id:",
            ["L_ApiKey"] = "api_key:",
            ["L_KeysHint"] = "Klucze potrzebne dla Gelbooru/Rule34; Danbooru i Safebooru działają bez nich",
            ["L_Cancel"] = "Anuluj",
            ["L_Save"] = "Zapisz",
            ["L_EditTip"] = "Edytuj",
            ["L_DeleteTip"] = "Usuń",
            ["S_Initial"] = "Wpisz tagi i kliknij „Następny”",
            ["S_Loading"] = "Ładowanie…",
            ["S_Nothing"] = "Nic nie znaleziono dla tych tagów",
            ["S_NoPreset"] = "Zaznacz co najmniej jedną stronę",
            ["S_WallpaperFail"] = "Nie udało się włączyć trybu tapety (nie znaleziono warstwy pulpitu).",
            ["S_WallpaperFailAttach"] = "Nie udało się włączyć trybu tapety: Windows odmówił osadzenia okna w pulpicie. Spróbuj zrestartować Eksploratora (explorer.exe) i uruchamiać BooruFrame bez uprawnień administratora.",
            ["S_ErrNet"] = "Błąd sieci: {0}",
            ["S_ErrGel"] = "Gelbooru wymaga kluczy API. Otwórz ustawienia strony i podaj user_id + api_key.",
            ["U_Sec"] = "s",
            ["U_Min"] = "min",
            ["Tray_Show"] = "Pokaż okno",
            ["Tray_Hide"] = "Ukryj okno",
            ["Tray_Wallpaper"] = "Tryb tapety",
            ["Tray_Prev"] = "Poprzedni obraz",
            ["Tray_Exit"] = "Wyjście",
        },
        [Lang.En] = new()
        {
            ["L_Tags"] = "Tags:",
            ["L_Sites"] = "Sites — random from checked:",
            ["L_AddSite"] = "＋ Add site",
            ["L_Filter"] = "Filter:",
            ["L_FilterNone"] = "No filter (all)",
            ["L_FilterModerate"] = "Moderate (no explicit)",
            ["L_FilterAggressive"] = "Strict (SFW only)",
            ["L_FilterCustom"] = "Custom ratings",
            ["L_ExcludeRatingsHint"] = "Check ratings to exclude from search:",
            ["L_IncludeTags"] = "Include tags in every search:",
            ["L_ExcludeTags"] = "Exclude tags from every search:",
            ["L_Preview"] = "Query preview:",
            ["L_TipDownload"] = "Download image",
            ["S_Saved"] = "Image saved",
            ["L_Scale"] = "Scaling:",
            ["L_ScaleFit"] = "Fit",
            ["L_ScaleStretch"] = "Stretch",
            ["L_ScaleCover"] = "Cover (crop)",
            ["L_Interval"] = "Interval:",
            ["L_HideErrors"] = "Hide errors after:",
            ["L_Never"] = "never",
            ["L_NoRepeat"] = "Don't repeat image:",
            ["L_Off"] = "off",
            ["U_Changes"] = "changes",
            ["L_HideAnim"] = "Hide loading animation",
            ["L_DesktopFrame"] = "Frame on the desktop (no normal window)",
            ["L_DesktopFrameHint"] = "The frame stops behaving like a normal window: no taskbar button, no Alt+Tab entry, and it drops onto the background below every other window once it loses focus. Clicking the frame raises it again. Does not apply in wallpaper mode — there the window is always a normal one.",
            ["L_Wallpaper"] = "Wallpaper mode (instead of window)",
            ["L_WallpaperHint"] = "The picture becomes a live desktop wallpaper — a layer of its own behind the icons. The app itself retreats to the tray: the window can be opened at any time and stays an ordinary, full window. Your native Windows wallpaper is never changed. Exit: Ctrl+Alt+F or the tray item.",
            ["L_Settings"] = "Settings",
            ["L_Close"] = "Close",
            ["L_TabSources"] = "Sources",
            ["L_TabDisplay"] = "Display",
            ["L_TabInfo"] = "Info",
            ["L_TagsHint"] = "Applies to all sites",
            ["L_Language"] = "Language:",
            ["L_InfoName"] = "Name:",
            ["L_InfoVersion"] = "Version:",
            ["L_InfoAuthor"] = "Author:",
            ["L_InfoRepo"] = "Repository:",
            ["L_InfoSupport"] = "Support:",
            ["L_TipPrev"] = "Previous image",
            ["L_TipNext"] = "Next image",
            ["L_TipPlay"] = "Start",
            ["L_TipStop"] = "Stop",
            ["L_TipSettings"] = "Settings",
            ["L_Aspect"] = "Orientation:",
            ["L_AspectAny"] = "All",
            ["L_AspectLandscape"] = "Landscape",
            ["L_AspectPortrait"] = "Portrait",
            ["L_AspectSquare"] = "Square",
            ["L_TipMin"] = "Minimize",
            ["L_TipMax"] = "Maximize",
            ["L_TipRestore"] = "Restore",
            ["L_TipClose"] = "Close",
            ["L_Start"] = "▶ Start",
            ["L_Stop"] = "⏹ Stop",
            ["L_Next"] = "⟳ Next",
            ["L_EditorNew"] = "New site",
            ["L_EditorEdit"] = "Edit site",
            ["L_Name"] = "Name:",
            ["L_Engine"] = "Engine:",
            ["L_Url"] = "Site URL:",
            ["L_Login"] = "login / user_id:",
            ["L_ApiKey"] = "api_key:",
            ["L_KeysHint"] = "Keys are needed for Gelbooru/Rule34; Danbooru and Safebooru work without them",
            ["L_Cancel"] = "Cancel",
            ["L_Save"] = "Save",
            ["L_EditTip"] = "Edit",
            ["L_DeleteTip"] = "Delete",
            ["S_Initial"] = "Enter tags and click “Next”",
            ["S_Loading"] = "Loading…",
            ["S_Nothing"] = "Nothing found for these tags",
            ["S_NoPreset"] = "Check at least one site",
            ["S_WallpaperFail"] = "Could not enter wallpaper mode (desktop background layer not found).",
            ["S_WallpaperFailAttach"] = "Could not enter wallpaper mode: Windows refused to embed the window into the desktop. Try restarting Explorer (explorer.exe) and running BooruFrame without administrator rights.",
            ["S_ErrNet"] = "Network error: {0}",
            ["S_ErrGel"] = "Gelbooru requires API keys. Open the site settings and set user_id + api_key.",
            ["U_Sec"] = "s",
            ["U_Min"] = "min",
            ["Tray_Show"] = "Show window",
            ["Tray_Hide"] = "Hide window",
            ["Tray_Wallpaper"] = "Wallpaper mode",
            ["Tray_Prev"] = "Previous image",
            ["Tray_Exit"] = "Exit",
        },
    };
}
